### PR TITLE
better text for spy

### PR DESCRIPTION
**Pull request by honsberg**

### CODE REVIEW

**Comment by dominionator** [comment]
I can't delete the README file for the project. It does need updating at some point, but not deleting.

**Comment by dominionator** [comment]
I also left a comment on your English Spy/Scrying Pool prompt change. It should have "for" instead of "at".

**Comment by honsberg** [comment]
you are right. im not english native speaker. ill correct it.

**Comment by honsberg** [comment]
i dont know how i can undelete the readme.

**Pull request closed without merging**
